baseurl = "http://ex-nerd.com/"
languageCode = "en-us"
title = "Chris Petersen"
theme = "hugo-future-imperfect"
preserveTaxonomyNames = true
paginate = 3
disqusShortname = ""
googleAnalytics = ""

pluralizelisttitles = false

# this doesn't seem to work on static files...
ignoreFiles = [ "\\.psd$" ]

[params]
    author = "Chris Petersen"
    # Sets the meta tag description, usually reserved for the main page
    description          = "Chris Petersen.  Definitely not an ex-nerd from Seattle."
    # This will appear on the top left of the navigation bar
    navbarTitle          = "Ex-nerd"
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = false
    # set this to the section name if section is not post
    # viewMorePostLink     = false

# Optional Params
    categoriesByCount    = true
    includeReadingTime   = false
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = false
    faviconVersion       = ""

    # Disable showing the social sharing links on blog posts
    socialShareDisabled = true

    # Load custom CSS or JavaScript files. This replaces the deprecated params
    # minifiedFilesCSS and minifiedFilesJS. The variable is an array so that you
    # can load multiple files if necessary. You can also load the standard theme
    # files by adding the value, "default".
    customCSS            = ["default", "/css/custom.css"]
    #customJS             = ["default", "/path/to/file"]

    # Loading min files for exampleSite
    #customCSS            = ["/css/main.min.css"]
    #customJS             = ["/js/main.min.js"]

# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[params.social]
    github          = "ex-nerd"
    bluesky         = "exnerd.bsky.social"
    #bitbucket       = "exnerd"
    #jsfiddle        = ""
    #codepen         = ""
    #foursquare      = ""
    #dribbble        = ""
    #deviantart      = ""
    #behance         = ""
    #flickr          = "ex-nerd"
    #instagram       = "exnerd"
    youtube         = "@ex-nerd"
    #vimeo           = ""
    #vine            = ""
    #medium          = ""
    #wordpress       = ""
    #tumblr          = ""
    #xing            = ""
    linkedin        = "exnerd"
    #slideshare      = ""
    stackoverflow   = "402727/ex-nerd"
    #reddit          = "ex-nerd"
    #pinterest       = "geek4026"
    #googleplus      = "ChrisPetersen_ex-nerd"
    #facebook        = "exnerd.xris"
    #facebook_admin  = ""
    #twitter_domain  = ""
    twitter         = "ex_nerd"
    #email           = ""

# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "Ex-nerd"

    paragraph = "As In: Irony"

    about     = ""

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.intro.pic]
    src       = "/img/logo.jpg"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = true
    imperfect = true
    width     = "200"
    alt       = "Ex-Nerd"

# Optional setting to adjust the number of recent posts on the sidebar.
# Set to 0 or false to disable recent posts.
# If left unset, the default value 5 will be used.
[params.postAmount]
    sidebar = false

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text
[[menu.main]]
    name = "About"
    url = "/about"
    identifier = "fas fa-user"
    weight = 1

[[menu.main]]
    name = "Tech"
    url = "/tech"
    identifier = "fas fa-power-off"
    weight = 2

[[menu.main]]
    name = "Food"
    url = "/food"
    identifier = "fas fa-utensils"
    weight = 3

[[menu.main]]
    name = "Making"
    url = "/making"
    identifier = "fas fa-hammer"
    weight = 4

[[menu.main]]
    name = "Diabetes"
    url = "/diabetes"
    identifier = "fas fa-tint"
    weight = 5

[[menu.main]]
    name = "Beer"
    url = "http://wingmanbrewers.com/"
    identifier = "fas fa-beer"
    weight = 98

[[menu.main]]
    name = "Resume"
    url = "/resume"
    identifier = "fas fa-file-alt"
    weight = 99

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.asciidocExt]
        backend = "html5"
        extensions = []
        failureLevel = "fatal"
        noHeaderOrFooter = true
        preserveTOC = false
        safeMode = "unsafe"
        sectionNumbers = false
        trace = false
        verbose = false
        workingFolderCurrent = false
        [markup.asciidocExt.attributes]
    [markup.blackFriday]
        angledQuotes = false
        footnoteAnchorPrefix = ""
        footnoteReturnLinkContents = ""
        fractions = true
        hrefTargetBlank = false
        latexDashes = true
        nofollowLinks = false
        noreferrerLinks = false
        plainIDAnchors = true
        skipHTML = false
        smartDashes = true
        smartypants = true
        smartypantsQuotesNBSP = false
        taskLists = true
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
        [markup.goldmark.parser]
            autoHeadingID = true
            autoHeadingIDType = "github"
        [markup.goldmark.parser.attribute]
            block = false
            title = true
        [markup.goldmark.renderer]
            hardWraps = false
            unsafe = true
            xhtml = false
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "monokai"
        tabWidth = 4
    [markup.tableOfContents]
        endLevel = 3
        ordered = false
        startLevel = 2

[module]
  [[module.mounts]]
    source = 'content'
    target = 'content'
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = './hugo-easy-gallery/layouts/shortcodes/figure.html'
    target = 'layouts/shortcodes/figure.html'
  [[module.mounts]]
    source = './hugo-easy-gallery/layouts/shortcodes/gallery.html'
    target = 'layouts/shortcodes/gallery.html'
  [[module.mounts]]
    source = './hugo-easy-gallery/layouts/shortcodes/load-photoswipe.html'
    target = 'layouts/shortcodes/load-photoswipe.html'
  [[module.mounts]]
    source = './hugo-easy-gallery/layouts/shortcodes/load-photoswipe-theme.html'
    target = 'layouts/shortcodes/load-photoswipe-theme.html'

  [[module.imports]]
    path = "./hugo-future-imperfect/"
